name: MacOS CPU
on: push
jobs:
  MacOS-Test:
    runs-on: macos-latest
    strategy:
      matrix:
        float_as_real_type: [OFF]
        build_type: [Release]
    steps:
      - name: "Install cmake 3.28.3"
        uses: lukka/get-cmake@v3.28.3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15.0"
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          repository: SC-SGS/PLSSVM
          path: PLSSVM
      - name: "Install Python dependencies"
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install argparse scikit-learn humanize numpy
      - name: "Configure PLSSVM using CMake"
        run: |
          mkdir PLSSVM/build
          cd PLSSVM/build
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_TARGET_PLATFORMS="cpu" -DPLSSVM_ENABLE_ASSERTS=ON -DPLSSVM_ENABLE_LANGUAGE_BINDINGS=ON -DPLSSVM_ENABLE_PERFORMANCE_TRACKING=ON -DPLSSVM_ENABLE_TESTING=ON -DPLSSVM_TEST_FILE_NUM_DATA_POINTS=50 -DPLSSVM_TEST_FILE_NUM_FEATURES=20 -DPLSSVM_ENABLE_LTO=OFF -DPLSSVM_USE_FLOAT_AS_REAL_TYPE=${{ matrix.float_as_real_type }} -DPLSSVM_ENABLE_FAST_MATH=OFF -DPLSSVM_ENABLE_OPENCL_BACKEND=OFF ..

