name: Windows MSVC CPU
on: push
jobs:
  MSVC-Test:
    runs-on: windows-latest
    strategy:
      matrix:
        float_as_real_type: [OFF]
        use_gemm: [OFF]
        build_type: [Release]
    steps:
      - name: "Install latest MSVC compiler"
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install visualstudio2022community visualstudio2022buildtools VisualCppBuildTools
      - name: load MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          vs-path: C:\Program Files\Microsoft Visual Studio\2022\Community
      - name: "Install cmake 3.25.2"
        uses: lukka/get-cmake@v3.28.3
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          path: Test
      - name: "Configure Test using CMake"
        shell: bash
        run: |
          mkdir Test/build
          cd Test/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_USE_FLOAT_AS_REAL_TYPE=${{ matrix.float_as_real_type }} -DPLSSVM_USE_GEMM=${{ matrix.use_gemm }} ..
          cmake --build .
