name: Windows MSVC CPU
on: push
jobs:
  MSVC-Test:
    runs-on: windows-2022
    strategy:
      matrix:
        float_as_real_type: [OFF]
        use_gemm: [OFF]
        build_type: [Release]
    steps:
      - name: "Test insall"
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd= @(
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64"
          )
          [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          # should be run twice
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      - name: "Install latest MSVC compiler"
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          toolset: 14.37
      - name: "Install cmake 3.25.2"
        uses: lukka/get-cmake@v3.28.3
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v4.1.1
        with:
          path: Test
      - name: "Configure Test using CMake"
        shell: bash
        run: |
          mkdir Test/build
          cd Test/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_USE_FLOAT_AS_REAL_TYPE=${{ matrix.float_as_real_type }} -DPLSSVM_USE_GEMM=${{ matrix.use_gemm }} ..
          cmake --build .
