name: Windows MSVC CPU
on: push
jobs:
  MSVC-Test:
    runs-on: windows-latest
    strategy:
      matrix:
        float_as_real_type: [ON, OFF]
        use_gemm: [ON, OFF]
        build_type: [Debug, Release]
    steps:
      - name: "Install latest MSVC compiler"
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: "Install cmake 3.25.2"
        uses: lukka/get-cmake@v3.25.2
      - name: "Clone the PLSSVM repository into PLSSVM/"
        uses: actions/checkout@v2
        with:
          path: Test
      - name: "Install Python dependencies"
        run: |
          py -m pip install --upgrade pip setuptools wheel
          py -m pip install -r Test/requirements.txt
      - name: "Configure Test using CMake"
        run: |
          mkdir Test/build
          cd Test/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DPLSSVM_USE_FLOAT_AS_REAL_TYPE=${{ matrix.float_as_real_type }} -DPLSSVM_USE_GEMM=${{ matrix.use_gemm }} .. ..
          echo "${GITHUB_WORKSPACE}/build" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo %PATH%
          ctest
